# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_egress_stream_response import CreateEgressStreamResponse
    from .create_ingress_stream_response import CreateIngressStreamResponse
    from .delete_egress_stream_response import DeleteEgressStreamResponse
    from .delete_ingress_stream_response import DeleteIngressStreamResponse
    from .egress_stream import EgressStream
    from .get_egress_stream_response import GetEgressStreamResponse
    from .get_ingress_stream_response import GetIngressStreamResponse
    from .google_protobuf_any import GoogleProtobufAny
    from .google_rpc_status import GoogleRpcStatus
    from .ingress_stream import IngressStream
    from .ingress_stream_status import IngressStreamStatus
    from .list_egress_streams_response import ListEgressStreamsResponse
    from .list_ingress_streams_response import ListIngressStreamsResponse
    from .mpeg_ts_ingress import MpegTsIngress
    from .mpeg_ts_settings import MpegTsSettings
    from .rtsp_egress import RtspEgress
    from .rtsp_ingress import RtspIngress
    from .rtsp_settings import RtspSettings
    from .srt_egress import SrtEgress
    from .srt_ingress import SrtIngress
    from .srt_settings import SrtSettings
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEgressStreamResponse": ".create_egress_stream_response",
    "CreateIngressStreamResponse": ".create_ingress_stream_response",
    "DeleteEgressStreamResponse": ".delete_egress_stream_response",
    "DeleteIngressStreamResponse": ".delete_ingress_stream_response",
    "EgressStream": ".egress_stream",
    "GetEgressStreamResponse": ".get_egress_stream_response",
    "GetIngressStreamResponse": ".get_ingress_stream_response",
    "GoogleProtobufAny": ".google_protobuf_any",
    "GoogleRpcStatus": ".google_rpc_status",
    "IngressStream": ".ingress_stream",
    "IngressStreamStatus": ".ingress_stream_status",
    "ListEgressStreamsResponse": ".list_egress_streams_response",
    "ListIngressStreamsResponse": ".list_ingress_streams_response",
    "MpegTsIngress": ".mpeg_ts_ingress",
    "MpegTsSettings": ".mpeg_ts_settings",
    "RtspEgress": ".rtsp_egress",
    "RtspIngress": ".rtsp_ingress",
    "RtspSettings": ".rtsp_settings",
    "SrtEgress": ".srt_egress",
    "SrtIngress": ".srt_ingress",
    "SrtSettings": ".srt_settings",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEgressStreamResponse",
    "CreateIngressStreamResponse",
    "DeleteEgressStreamResponse",
    "DeleteIngressStreamResponse",
    "EgressStream",
    "GetEgressStreamResponse",
    "GetIngressStreamResponse",
    "GoogleProtobufAny",
    "GoogleRpcStatus",
    "IngressStream",
    "IngressStreamStatus",
    "ListEgressStreamsResponse",
    "ListIngressStreamsResponse",
    "MpegTsIngress",
    "MpegTsSettings",
    "RtspEgress",
    "RtspIngress",
    "RtspSettings",
    "SrtEgress",
    "SrtIngress",
    "SrtSettings",
]
