# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_ids_selector import EntityIdsSelector


class AgentStreamRequest(UniversalBaseModel):
    """
    The request to establish a streaming connection using Server-Sent Events (SSE) for receiving Tasks as an agent.

    This message defines the criteria for which tasks the agent wants to receive,
    typically specified using the agent's `entityId`. When an agent
    establishes this connection, the Lattice will stream relevant tasks
    to that agent to execute, cancel, or complete.
    """

    agent_selector: typing_extensions.Annotated[
        typing.Optional[EntityIdsSelector], FieldMetadata(alias="agentSelector")
    ] = pydantic.Field(alias="agentSelector", default=None)
    """
    The selector criteria to determine which tasks the agent receives.
    """

    heartbeat_interval_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="heartbeatIntervalMs")
    ] = pydantic.Field(alias="heartbeatIntervalMs", default=None)
    """
    The time interval, defined in seconds, that determines the frequency at which to send heartbeat events. Defaults to 30s.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
