# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateEgressStreamResponse,
        CreateIngressStreamResponse,
        DeleteEgressStreamResponse,
        DeleteIngressStreamResponse,
        EgressStream,
        GetEgressStreamResponse,
        GetIngressStreamResponse,
        GoogleProtobufAny,
        GoogleRpcStatus,
        IngressStream,
        IngressStreamStatus,
        ListEgressStreamsResponse,
        ListIngressStreamsResponse,
        MpegTsIngress,
        MpegTsSettings,
        RtspEgress,
        RtspIngress,
        RtspSettings,
        SrtEgress,
        SrtIngress,
        SrtSettings,
    )
    from .errors import (
        BadRequestError,
        ConflictError,
        ForbiddenError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
    )
    from . import video
_dynamic_imports: typing.Dict[str, str] = {
    "BadRequestError": ".errors",
    "ConflictError": ".errors",
    "CreateEgressStreamResponse": ".types",
    "CreateIngressStreamResponse": ".types",
    "DeleteEgressStreamResponse": ".types",
    "DeleteIngressStreamResponse": ".types",
    "EgressStream": ".types",
    "ForbiddenError": ".errors",
    "GetEgressStreamResponse": ".types",
    "GetIngressStreamResponse": ".types",
    "GoogleProtobufAny": ".types",
    "GoogleRpcStatus": ".types",
    "IngressStream": ".types",
    "IngressStreamStatus": ".types",
    "InternalServerError": ".errors",
    "ListEgressStreamsResponse": ".types",
    "ListIngressStreamsResponse": ".types",
    "MpegTsIngress": ".types",
    "MpegTsSettings": ".types",
    "NotFoundError": ".errors",
    "RtspEgress": ".types",
    "RtspIngress": ".types",
    "RtspSettings": ".types",
    "ServiceUnavailableError": ".errors",
    "SrtEgress": ".types",
    "SrtIngress": ".types",
    "SrtSettings": ".types",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "video": ".video",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadRequestError",
    "ConflictError",
    "CreateEgressStreamResponse",
    "CreateIngressStreamResponse",
    "DeleteEgressStreamResponse",
    "DeleteIngressStreamResponse",
    "EgressStream",
    "ForbiddenError",
    "GetEgressStreamResponse",
    "GetIngressStreamResponse",
    "GoogleProtobufAny",
    "GoogleRpcStatus",
    "IngressStream",
    "IngressStreamStatus",
    "InternalServerError",
    "ListEgressStreamsResponse",
    "ListIngressStreamsResponse",
    "MpegTsIngress",
    "MpegTsSettings",
    "NotFoundError",
    "RtspEgress",
    "RtspIngress",
    "RtspSettings",
    "ServiceUnavailableError",
    "SrtEgress",
    "SrtIngress",
    "SrtSettings",
    "TooManyRequestsError",
    "UnauthorizedError",
    "video",
]
