# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from ...types.agent_stream_heartbeat_data import AgentStreamHeartbeatData
from ...types.agent_task_request import AgentTaskRequest


class ListenAsAgentStreamResponse_Heartbeat(UniversalBaseModel):
    """
    The stream event response.
    """

    event: typing.Literal["heartbeat"] = "heartbeat"
    data: AgentStreamHeartbeatData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ListenAsAgentStreamResponse_AgentRequest(UniversalBaseModel):
    """
    The stream event response.
    """

    event: typing.Literal["agent_request"] = "agent_request"
    data: AgentTaskRequest

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ListenAsAgentStreamResponse = typing_extensions.Annotated[
    typing.Union[ListenAsAgentStreamResponse_Heartbeat, ListenAsAgentStreamResponse_AgentRequest],
    pydantic.Field(discriminator="event"),
]
update_forward_refs(ListenAsAgentStreamResponse_AgentRequest)
